---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: assistant-relay-pv
  labels:
    directory: assistant-relay
spec:
  storageClassName: local
  capacity:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/pi/containers/assistant-relay

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assistant-relay-claim
spec:
  storageClassName: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      directory: assistant-relay

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assistant-relay
  labels:
    app: assistant-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assistant-relay
  template:
    metadata:
      labels:
        app: assistant-relay
        name: assistant-relay
    spec:
      containers:
        - name: assistant-relay
          image: apipa169/assistant-relay:latest
          securityContext:
            privileged: true
          volumeMounts:
            - name: assistant-relay-local-containers-volume
              mountPath: "/etc/assistant-relay"
      volumes:
        - name: assistant-relay-local-containers-volume
          persistentVolumeClaim:
            claimName: assistant-relay-claim

---
apiVersion: v1
kind: Service
metadata:
  name: assistant-relay
spec:
  selector:
    app: assistant-relay
  ports:
    - port: 3000
      targetPort: 3000
      name: assistant-relay
  externalIPs:
    - <ip>
