apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  # imagePullSecrets:
  #   - name: github-registry
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: '200Mi'
        requests:
          memory: '100Mi'
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
  - host: nginx1.pi1.local
    http:
      paths:
      - path: /(.*)
        pathType: Exact  
        backend:
          service:
            name: nginx
            port: 
              number: 80
  - host: nginx2.pi1.local
    http:
      paths:
      - path: /(.*)
        pathType: Exact  
        backend:
          service:
            name: nginx
            port: 
              number: 80
