apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webapp-color
  name: webapp-color
spec:
  containers:
  - name: webapp-color
    image: kodecloud/webapp-color
    env:
      - name: APP_COLOR
        valueFrom:
          configMapKeyRef:
            name: webapp-config-map
            key: APP_COLOR
