apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-user-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-user
# subjects:
# - apiGroup: rbac.authorization.k8s.io
#   kind: Group
#   name: system:bootstrappers:kubeadm:default-node-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-user
  namespace: default
rules:
- apiGroups:
  - "pods"
  resourceNames:
  - dev-user
  resources:
  - pods
  verbs:
  - get
  - list
  - create
  - delete

