apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-deployment
  labels:
    app: nginx-test-deployment
spec:
  selector:
    matchLabels:
      app: nginx-test-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-test-deployment
    spec:
      containers:
      - name: nginx-test-deployment
        image: nginx
        ports:
          - containerPort: 80
