# k create configmap redis-config --from-literal=<KEY=value>
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  # #     maxSurge: 2
  #     maxUnavailable: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
      - name: redis-config
        emptyDir: {}
      - name: data
        emptyDir: {}
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - name: redis
          containerPort: 6379
        resources:
          limits:
            cpu: .2
          requests:
            cpu: .2
        volumeMounts:
        - name: data
          mountPath: /redis-master-data
