---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
  namespace: homeassistant
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-local-volume
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  volumeMode: Filesystem
  storageClassName: local
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/pi/containers/pihole"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-local-claim
  namespace: homeassistant
spec:
  storageClassName: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      app: homeassistant
