apiVersion: v1
kind: Pod
metadata:
  name: ackee
  labels:
    app: ackee
spec:
  containers:
    - name: ackee
      image: electerious/ackee:3.4.2
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
      ports:
        - containerPort: 80
      env:
        - name: NODE_ENV
          value: production
        - name: ACKEE_MONGODB
          value: mongodb://0.0.0.0:27017/ackee
---
apiVersion: v1
kind: Pod
metadata:
  name: ackee-mongo
  labels:
    app: ackee
spec:
  containers:
    - name: ackee-mongo
      image: mongo
      command:
        - mongod
        - "--bind_ip"
        - "0.0.0.0"
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
      ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: ackee-mongo
  labels:
    app: ackee
spec:
  selector:
    app: ackee
  ports:
    - port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: ackee
  labels:
    app: ackee
spec:
  type: ClusterIP
  selector:
    app: ackee
  ports:
    - name: ackee
      port: 80
      protocol: TCP
      targetPort: 80

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ackee
#   labels:
#     app: ackee
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
#     ingress.kubernetes.io/add-base-url: "true"
# spec:
#   rules:
#     - host: ackee-koenverburg.cloud.okteto.net
#       http:
#         paths:
#           - path: /(.*)
#             pathType: Exact
#             backend:
#               service:
#                 name: ackee
#                 port:
#                   number: 80
