apiVersion: v1
kind: Pod
metadata:
  name: ackee
  labels:
    app: ackee
spec:
  containers:
    - name: ackee
      image: electerious/ackee:3.4.2
      # securityContext:
      #   privileged: true
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
      ports:
        - name: http 
          protocol: TCP
          containerPort: 3000
      env:
        - name: NODE_ENV
          value: production

        - name: ACKEE_PORT
          value: "3000"

        - name: ACKEE_USERNAME
          value: "ackee"

        - name: ACKEE_PASSWORD
          value: "ackee"

        - name: ACKEE_MONGODB
          value: mongodb://admin:password@ackee-mongo:27017/ackee
---
apiVersion: v1
kind: Service
metadata:
  name: ackee-svc
  labels:
    app: ackee
spec:
  type: ClusterIP
  selector:
    app: ackee
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ackee
  labels:
    app: ackee
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
    - host: ackee-koenverburg.cloud.okteto.net
      http:
        paths:
          - path: /(.*)
            pathType: Exact
            backend:
              service:
                name: ackee-svc
                port:
                  number: 80
