# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: ackee-mongo-pv
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 1Gi
#   hostPath:
#     path: /data/mongo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ackee-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ackee-mongo
  labels:
    app: ackee
spec:
  type: NodePort
  selector:
    app: ackee
  ports:
    - port: 27017
      nodePort: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Pod
metadata:
  name: ackee-mongo
  labels:
    app: ackee
spec:
  containers:
    - name: ackee-mongo
      image: mongo
      command:
        - mongod
        - "--bind_ip"
        - "0.0.0.0"
        - "--dbpath"
        - "/data/db"
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
      ports:
        - name: mongo
          # hostPort: 27017
          containerPort: 27017
      volumeMounts:
        - name: "ackee-mongo-path"
          mountPath: "/data/db"
      env:
        - name: MONGODB_USERNAME
          value: "admin"

        - name: MONGODB_PASSWORD
          value: "password"
  volumes:
    - name: "ackee-mongo-path"
      persistentVolumeClaim:
        claimName: "ackee-mongo-pvc"
