apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: db-secret
  annotations:
    kubernetes.io/service-account.name: default
data:
  DB_Host: c3FsMDE=
  DB_User: cm9vdA==
  DB_Password: cGFzc3dvcmQxMjM=

