apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  annotations:
    kubernetes.io/service-account.name: default
spec:
  containers:
  - name: webapp-pod
    image: kodekloud/simple-webapp-mysql
    envFrom:
    - secretRef:
        name: db-secret
