---
- name: Install packages that allow apt to be used over HTTPS
  become: yes
  apt:
    state: present
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add an apt signing key for Docker
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install docker and its dependencies
  become: yes
  apt:
    state: present
    update_cache: yes
    name:
      - docker
      # - docker-cli
      # - docker-ce-cli
      # - containerd.io
