apiVersion: batch/v1
kind: CronJob
metadata:
  name: throw-dice-cron-job
spec:
  schedule: '30 21 * * *'
  jobTemplate:
    completions: 3
    parallelism: 3
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            -  image: kodekloud/throw-dice
               name: throw-dice
