name: NixOS (Pi's)

on:
  push:
    branches: main

jobs:
  pi-3b:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - name: Check nix.conf
        run: cat /etc/nix/nix.conf

      - uses: myci-actions/add-deb-repo@4
        with:
          repo: deb http://http.us.debian.org/debian sid main non-free contrib
          repo-name: debian-sid
          keys: 04EE7237B7D453EC

      - name: Install qemu static
        run: |
          sudo apt -y install qemu-user-static

      - name: Test binfmt availability
        run: |
          cat /proc/sys/fs/binfmt_misc/qemu-aarch64
          /usr/bin/qemu-aarch64-static --version

      - name: Build SD Image
        run: |
          nix-build '<nixpkgs/nixos>'  \
            -A config.system.build.sdImage \
            -I nixos-config=./nixos/pi3b/configuration.nix \
            --argstr system aarch64-linux \
            --option sandbox false

      - uses: actions/upload-artifact@v2
        with:
          name: sd-image.img
          path: ./result/sd-image/*.img*
